version: "3.8"

services:
  rest-test:
    build: .
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - mongo_db
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - "27018:27017"
  prometheus:
    image: "prom/prometheus:latest"
    restart: always
    depends_on:
      - rest-test
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/rest-test_prometheus-data
      - prometheus-data:/rest-test_prometheus-data
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana:latest"
    restart: always
    depends_on:
      - rest-test
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
