version: "3.8"

services:
  rest-test:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - "27018:27017"
